#!/bin/bash

# From: https://docs.docker.com/docker-cloud/builds/advanced/
#
# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "IMAGE_NAME: $IMAGE_NAME"
echo "SOURCE_BRANCH: $SOURCE_BRANCH"
echo "SOURCE_COMMIT: $SOURCE_COMMIT"
echo "COMMIT_MSG: $COMMIT_MSG"
echo "DOCKER_REPO: $DOCKER_REPO"
echo "DOCKER_TAG: $DOCKER_TAG"

local vcs_url=$(git remote get-url origin 2> /dev/null || echo "https://github.com/pinterb/dockerfiles")
echo "Build hook running"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_URL=$vcs_url \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg VERSION="2.62" \
             -t $IMAGE_NAME .
