FROM vault:0.6.1

MAINTAINER Brad Pinter <brad.pinter@gmail.com>

LABEL vendor="HashiCorp" \
      com.hashicorp.vault.version="0.6.1" \
      com.hashicorp.vault.release-date="2016-08-22"

## Expose the config volume
VOLUME ["/vault/config"]
