# phusion-base
#
# VERSION      0.0.3

FROM pinterb/phusion-base:0.0.3

MAINTAINER Brad Pinter brad.pinter@gmail.com

ENV HOME /root
ENV DEBIAN_FRONTEND noninteractive
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8


### enable repos and update


### prepare system


### install packages


### configure


### finalize build


### run our init
CMD ["/sbin/my_init"]
