# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "app" do |v|
    v.vm.provider "docker" do |d|
      d.image   = ENV['VAGRANT_SERVERSPEC_DOCKER_TEST_IMAGE']
      d.cmd     = ["/sbin/my_init", "--enable-insecure-key"]
      d.has_ssh = true
    end

    v.ssh.username = "root"
    v.ssh.private_key_path = "phusion.key"
    v.ssh.port = "22"

    v.vm.provision :serverspec do |spec|
      spec.pattern = '*_spec.rb'
    end
  end
end
